force-app/main/default/objects/SQX_Part__c/SQX_Part__c.object-meta.xml
<CustomObject>
    <label>Part</label>
    <nameField>
        <label>Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SQX_Part__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <label>Part Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SQX_Part__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Parts</relationshipLabel>
    <relationshipName>Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PartToProductBatch.cls
public with sharing class PartToProductBatch implements Database.Batchable<SObject> {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id, Name, Part_Number__c, Active__c, Product2__c
            FROM SQX_Part__c
            WHERE Active__c = true
        ]);
    }

    public void execute(Database.BatchableContext bc, List<SQX_Part__c> scope) {
        if (hasAccess()) {
            PartToProductService.syncPartsWithProducts(scope);
        }
    }

    public void finish(Database.BatchableContext bc) {}

    private Boolean hasAccess() {
        return (UserInfo.getProfileId() == [
            SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1
        ].Id)
        || FeatureManagement.checkPermission('CQ_Product_Admin');
    }
}